name: Build and Deploy create-product to EC2 from MAIN

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build the Docker image with 'latest' tag
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/create-product:${{ env.IMAGE_TAG }} .

      # Push the image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/create-product:${{ env.IMAGE_TAG }}

      # Prepare SSH key
      - name: Setup SSH key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 400 key.pem

      # SSH into EC2 and deploy the container from Docker Hub
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            set -e

            echo "📦 Deploying create-product using Docker Hub image (latest)..."

            # Install Docker if necessary
            if ! command -v docker &> /dev/null; then
              echo "🛠 Installing Docker..."
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl enable docker
              sudo systemctl start docker
            else
              echo "✅ Docker is already installed."
            fi

            # Stop and remove old container if it exists
            sudo docker rm -f create-product || true

            # Pull the latest image from Docker Hub
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/create-product:${{ env.IMAGE_TAG }}

            # Run the new container
            sudo docker run -d --name create-product \
              -p 4002:4002 \
              --restart always \
              -e MONGODB_URI=mongodb://52.21.72.12:27017 \
              -e DB_NAME=toyshop_db \
              -e PORT=4002 \
              ${{ secrets.DOCKER_USERNAME }}/create-product:${{ env.IMAGE_TAG }}

            echo "✅ create-product deployed successfully (main)"
            sudo docker ps -a
          EOF